# Exercise 07 

### Instructions


#### Using the data for Presidential Elections from 1972-2012 complete the following tasks
- Estimate a two-state discrete Markov chain (with the states being Democrat and Republican).

- Estimate the steady-state distribution for the chain.

- Use the 2012 observations by state together with your estimated chain and the electoral votes for each state to predict the 2016 election. Run 100 simulated elections. What is the share of elections won by the Democrat?

##### Assumptions:
- All US states follow the same chain
- All US states are independent of their neighbors

### 1. Estimate a two-state discrete Markov chain (with the states being Democrat and Republican).

In [1]:

"""
All of the following pulled form class lectures and class repos
"""
#INCLUDE VARIABLES / NUMPY LIBRARY

import numpy as np

R = 1 # Republicans
D = 0 # Democrats

#Data from Wiki Table

StateElection = [
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,D,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,D,R,R,R,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,R,R,R,D,D,D,D,D,D],
[D,D,D,D,D,D,D,D,D,D,D],
[R,D,R,R,R,R,D,R,R,D,D],
[R,D,D,R,R,D,R,R,R,R,R],
[R,D,D,R,D,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,D,R],
[R,R,R,R,D,D,D,D,R,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,D,R,R,D,D,D,D,D,D],
[D,D,R,R,D,D,D,D,D,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,D,D,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,R,R,D,D],
[R,R,R,R,R,D,D,R,D,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,D,D,D,R,D,D],
[R,D,R,R,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,D,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,D,D,D,D,D,D,D],
[R,D,R,R,R,D,D,D,D,D,D],
[R,D,D,R,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,D,D],
[R,R,R,R,D,D,D,D,D,D,D],
[R,D,D,R,D,D,D,R,R,R,R],
[R,D,R,R,D,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,R,R]]

StateNames = [
"Alabama",
"Alaska",
"Arizona",
"Arkansas",
"California",
"Colorado",
"Connecticut",
"Delaware",
"D.C.",
"Florida",
"Georgia",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Maryland",
"Massachusetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada",
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"North Carolina",
"North Dakota",
"Ohio",
"Oklahoma",
"Oregon",
"Pennsylvania",
"Rhode Island",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming"]

# Wiki State Electors 

STElect = [9, 3, 11, 6, 5, 9, 7, 3, 3, 29, 16, 4, 4, 20, 11, 6,
           6, 8, 8, 4, 10, 11, 16, 10, 6, 10, 3, 5, 6, 4, 14, 5,
           29, 15, 3, 18, 7, 7, 20, 4, 9, 3, 11, 38, 6, 3, 13, 12,
           5, 10, 3]
# Line [21] NumPy Lecture Notes

StateHis = np.array(StateElection) #Stores Appropriate Values Of Given Array

StateLast = [v[-1] for v in StateHis]

transitions = np.zeros((2,2))
for state in StateHis:
    for i in range(1, len(state)):
        transitions[state[i-1], state[i]] += 1


row_sum = transitions.sum(axis=1) 

P = np.dot(np.diag(1/row_sum), transitions)

print("Answer 1:")
print(P)

Answer 1:
[[ 0.77900552  0.22099448]
 [ 0.19756839  0.80243161]]


In [2]:
# Methods for Markov

def get_markov_states(p_matrix, current_states):
   
    # Generate a set of random values
    random_values = np.random.rand(len(current_states))
    
    # Create an array that gives true if the state will be 1, false if it will be 0
    is_one = np.array([(r > p_matrix[int(h),0]) for h,r in zip(current_states,random_values)])
    
    # Set the output array values
    result = np.zeros(len(current_states))
    result[is_one] = 1
    
    return result
########################################################################
def eval_electoral_college(elector_counts, state_status):
   
    result = np.zeros(int(max(state_status))+1)
    
    for count, status in zip(elector_counts, state_status):
        result[int(status)] += count
    return result
########################################################################
def simulate_elections(p_matrix, initial_state, elector_counts, election_count):
    
    dem_wins = 0
    rep_wins = 0

    for i in range(election_count):
        # Use a unique seed for each trial run, but keep things repeatable
        # The +100 is just an adjustment to make a tie show up in the results
        #  for a 100-election test
        np.random.seed(i+100)
        
        vote_directions = get_markov_states(p_matrix,initial_state)
        electoral_totals = eval_electoral_college(elector_counts, vote_directions)
        
        #index of one represents Republican and index of zero represents Democrat
        if(electoral_totals[1] > electoral_totals[0]):
            rep_wins += 1
        elif(electoral_totals[0] > electoral_totals[1]):
            dem_wins += 1
            
    return dem_wins, rep_wins
#row|Column



#### 2. Estimate the steady-state distribution for the chain.

In [3]:
#determine steady-state probabilities after 10 interations
DemSumTotal = 0
RepSumTotal = 0
# P Matrix of 2D Array
P2 = P.dot(P)
for i in range(9):
    DemSumTotal = 0
    RepSumTotal = 0
    print(" [Democrats %|Repubican %]")
    print(P2)
    P2 = P2.dot(P2)
    DemSumTotal = ((P2[0][0] + P2[1][0]) / 2)
    RepSumTotal = ((P2[0][1] + P2[1][1]) / 2)
    print
    print ('Democrat Prediction: %s'% DemSumTotal)
    print('Republic Prediction: %s'% RepSumTotal)
    print('------------------------------')

 [Democrats %|Repubican %]
[[ 0.65051113  0.34948887]
 [ 0.31244199  0.68755801]]

Democrat Prediction: 0.475214354861
Republic Prediction: 0.524785645139
------------------------------
 [Democrats %|Repubican %]
[[ 0.53235973  0.46764027]
 [ 0.41806898  0.58193102]]

Democrat Prediction: 0.472381585003
Republic Prediction: 0.527618414997
------------------------------
 [Democrats %|Repubican %]
[[ 0.47891277  0.52108723]
 [ 0.4658504   0.5341496 ]]

Democrat Prediction: 0.472020822924
Republic Prediction: 0.527979177076
------------------------------
 [Democrats %|Repubican %]
[[ 0.47210614  0.52789386]
 [ 0.47193551  0.52806449]]

Democrat Prediction: 0.472016048959
Republic Prediction: 0.527983951041
------------------------------
 [Democrats %|Repubican %]
[[ 0.47201606  0.52798394]
 [ 0.47201603  0.52798397]]

Democrat Prediction: 0.472016048144
Republic Prediction: 0.527983951856
------------------------------
 [Democrats %|Repubican %]
[[ 0.47201605  0.52798395]
 [ 0.47201605  0

#### 3. Use the 2012 observations by state together with your estimated chain and the electoral votes for each state to predict the 2016 election. Run 100 simulated elections. What is the share of elections won by the Democrat?

In [4]:
dem_wins, rep_wins= simulate_elections(P, StateLast, STElect, 100)
print("Democratic wins: ", dem_wins)
print(" Republican wins: ", rep_wins)

('Democratic wins: ', 67)
(' Republican wins: ', 32)
