In [18]:
#import necessary package for assingment 7
import numpy as np

In [19]:
#Republicans are assigned value of 1 and Democrats are assigned value of zero
R = 1
D = 0

In [20]:
# Data:
state_history = [
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,D,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,D,R,R,R,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,R,R,R,D,D,D,D,D,D],
[D,D,D,D,D,D,D,D,D,D,D],
[R,D,R,R,R,R,D,R,R,D,D],
[R,D,D,R,R,D,R,R,R,R,R],
[R,D,D,R,D,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,D,R],
[R,R,R,R,D,D,D,D,R,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,D,R,R,D,D,D,D,D,D],
[D,D,R,R,D,D,D,D,D,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,D,D,D,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,R,R,R,R,D,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,R,R,D,D],
[R,R,R,R,R,D,D,R,D,D,D],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,D,D,D,R,D,D],
[R,D,R,R,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,D,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,D,D],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,D,D,D,D,D,D,D],
[R,D,R,R,R,D,D,D,D,D,D],
[R,D,D,R,D,D,D,D,D,D,D],
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,D,R,R,R,D,D,R,R,R,R],
[R,D,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,R,R,R,R,R,R],
[R,R,R,R,R,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,D,D],
[R,R,R,R,D,D,D,D,D,D,D],
[R,D,D,R,D,D,D,R,R,R,R],
[R,D,R,R,D,D,D,D,D,D,D],
[R,R,R,R,R,R,R,R,R,R,R]]

In [22]:
#place values for D and R in numpy array
state_history = np.array(state_history)
state_history

array([[1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0,

In [23]:
#create variable for last votes for each state
state_last_vote = [v[-1] for v in state_history]

In [24]:
#create list of state names
state_names = [
"Alabama",
"Alaska",
"Arizona",
"Arkansas",
"California",
"Colorado",
"Connecticut",
"Delaware",
"D.C.",
"Florida",
"Georgia",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Maryland",
"Massachusetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada",
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"North Carolina",
"North Dakota",
"Ohio",
"Oklahoma",
"Oregon",
"Pennsylvania",
"Rhode Island",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"Utah",
"Vermont",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming"]

In [6]:
# Same order as state_names.
# Data from 2012 column of https://en.wikipedia.org/wiki/Electoral_College_(United_States)#Chronological_table
state_electors = [9, 3, 11, 6, 5, 9, 7, 3, 3, 29, 16, 4, 4, 20, 11, 6, 6, 8, 8, 4, 10, 11, 16, 10, 6, 10, 3, 5, 6, 4, 14, 5, 29, 15, 3, 18, 7, 7, 20, 4, 9, 3, 11, 38, 6, 3, 13, 12, 5, 10, 3]

In [25]:
#b = (state_history == R) * 1
#b

In [26]:
#determine the transition matrix for the election
transitions = np.zeros((2,2))
for state in state_history:
    for i in range(1, len(state)):
        transitions[state[i-1], state[i]] += 1
print(transitions)

[[ 141.   40.]
 [  65.  264.]]


In [27]:
#sum the rows of the transition matrix
row_sum = transitions.sum(axis=1) 
print(row_sum)

[ 181.  329.]


In [10]:
#construct the probability matrix
P = np.dot(np.diag(1/row_sum), transitions)
print(P)

[[ 0.77900552  0.22099448]
 [ 0.19756839  0.80243161]]


In [28]:
#necessary functions for markov chain analysis

def get_markov_states(p_matrix, current_states):
    """
    Create a set of results based on a set of current states and a probability matrix
    
    Inputs:
    p_matrix: 2x2 matrix
       Row index is initial state, column index is resulting state
    current_states: 1d array
       Values are the current states, must be 1 or 0
       
    Output:
    resulting_state: 1d array
        The final state of each element in current_state, based on the probability matrix
    """
    # Generate a set of random values
    random_values = np.random.rand(len(current_states))
    
    # Create an array that gives true if the state will be 1, false if it will be 0
    is_one = np.array([(r > p_matrix[int(h),0]) for h,r in zip(current_states,random_values)])
    
    # Set the output array values
    result = np.zeros(len(current_states))
    result[is_one] = 1
    
    return result

def eval_electoral_college(elector_counts, state_status):
    """
    Tally up electoral votes based on an array of state results
    
    Inputs:
    elector_counts: 1d array
       Contains Electoral College elector counts for each state
    state_status: 1d array
       Contains the vote result for each state, where the value will be the index of the
       output array that this state's elctoral votes will be added to.
       
    Output:
    vote_tally: 1d array
        Votes recieved by each party, where index is the party ID used by state_status
    """
    result = np.zeros(int(max(state_status))+1)
    
    for count, status in zip(elector_counts, state_status):
        result[int(status)] += count
    return result

def simulate_elections(p_matrix, initial_state, elector_counts, election_count):
    """
    Run multiple simulated elections, return the win tallies
    
    Inputs:
    p_matrix: 2x2 matrix
        Row index is initial state, column index is resulting state
    current_states: 1d array
        Values are the current states, must be 1 or 0
    elector_counts: 1d array
        Contains Electoral College elector counts for each state
    election_count: integer
        Number of elections to simulate.
       
    Output:
    dem_wins: integer
        Number of wins by the party with index D
    rep_wins: integer
        Number of wins by the party with index R
    ties: integer
        Number of times the two parties tied
    """
    dem_wins = 0
    rep_wins = 0
    ties = 0
    for i in range(election_count):
        # Use a unique seed for each trial run, but keep things repeatable
        # The +100 is just an adjustment to make a tie show up in the results
        #  for a 100-election test
        np.random.seed(i+100)
        
        vote_directions = get_markov_states(p_matrix,initial_state)
        electoral_totals = eval_electoral_college(elector_counts, vote_directions)
        
        #index of one represents Republican and index of zero represents Democrat
        if(electoral_totals[1] > electoral_totals[0]):
            rep_wins += 1
        elif(electoral_totals[0] > electoral_totals[1]):
            dem_wins += 1
        else:
            ties += 1
            
    return dem_wins, rep_wins, ties

In [33]:
#determine steady-state probabilities after 10 interations
P2 = P.dot(P)
for i in range(9):
    print(P2)
    print('------------------------------')
    P2 = P2.dot(P2)

[[ 0.65051113  0.34948887]
 [ 0.31244199  0.68755801]]
------------------------------
[[ 0.53235973  0.46764027]
 [ 0.41806898  0.58193102]]
------------------------------
[[ 0.47891277  0.52108723]
 [ 0.4658504   0.5341496 ]]
------------------------------
[[ 0.47210614  0.52789386]
 [ 0.47193551  0.52806449]]
------------------------------
[[ 0.47201606  0.52798394]
 [ 0.47201603  0.52798397]]
------------------------------
[[ 0.47201605  0.52798395]
 [ 0.47201605  0.52798395]]
------------------------------
[[ 0.47201605  0.52798395]
 [ 0.47201605  0.52798395]]
------------------------------
[[ 0.47201605  0.52798395]
 [ 0.47201605  0.52798395]]
------------------------------
[[ 0.47201605  0.52798395]
 [ 0.47201605  0.52798395]]
------------------------------


In [35]:
# Check the election results using the steady-state probability matrix
dem_wins, rep_wins, ties = simulate_elections(P2, state_last_vote, state_electors, 10000)
print("Democratic wins: ", dem_wins, " Republican wins: ", rep_wins, " Ties: ",ties)

('Democratic wins: ', 3696, ' Republican wins: ', 6234, ' Ties: ', 70)


In [41]:
#Predict the election results after 100 interations
#create list for electoral vote count for R
#create list of states won by R
r_results = [] 
r_state_counts = [] 

#number of iterations set to 100
chain_length = 100

state_status = state_last_vote
for i in range(5):
    np.random.seed(i)
    r_list = []
    r_count_list = []
    
    # Run things out for chain_length election cycles
    for i in range(chain_length):
        state_status = get_markov_states(P,state_status)
        electoral_totals = eval_electoral_college(state_electors, state_status)
        r_list.append(electoral_totals[1])
        r_count_list.append(sum(state_status)/50)
    r_results.append(r_list)
    r_state_counts.append(r_count_list)

In [43]:
dem_wins,rep_wins,ties = simulate_elections(P, state_last_vote, state_electors, 100)
print("Democratic wins: ", dem_wins, " Republican wins: ", rep_wins, " Ties: ",ties)

('Democratic wins: ', 67, ' Republican wins: ', 32, ' Ties: ', 1)
